TARGET_INSTALL_PATH = /usr/bin
DATA_INSTALL_PATH = /usr/share/qpdfview
LAUNCHER_INSTALL_PATH = /usr/share/applications
MANUAL_INSTALL_PATH = /usr/share/man/man1

DEFINES += PAINT_LINKS=1
DEFINES += RENDER_FROM_DISK=1
