.\" Process this file with
.\" groff -man -Tascii qpdfview.1
.\"
.TH QPDFVIEW 1 "March 2012"
.SH NAME
qpdfview \- tabbed PDF viewer
.SH SYNOPSIS
.B qpdfview
.I [options] [file(s)[#page[#top]]]
.SH DESCRIPTION
.B qpdfview
is a simple document viewer for PDF documents. It uses the poppler library for rendering.
.SH OPTIONS
.IP --unique
If an instance of qpdfview is started with this option, any files that are opened using this option afterwards, are opened as tabs in this same window. If a file is already opened in a tab of the respective window, it is merely reloaded using this option.
.IP [file(s)[#page[#top]]]
Specifies the files to open when qpdfview starts. If this is not specified, qpdfview will open a blank window. Multiple files can be loaded in separate tabs if the file names are separated by spaces. The optional parameter
.I #page
opens the file at the given page. The optional parameter
.I #top
can take values between 0 and 1 and opens the page with the given position aligned to the top of the tab. (See examples.)
.SH CONFIGURATION FILE
qpdfview uses a configuration file usually located at
.RS
"~/.config/qpdfview/qpdfview.conf",
.RE
which allows configuration of the toolbars and thumbnails.

The keys "fileToolBar", "editToolBar" and "viewToolBar" are added to the section "mainWindow". Their values are comma-separated lists. The default (available) entries are:
.RS
fileToolBar: openInNewTab, refresh (open, saveCopy, print)
.RS
.RE
editToolBar: currentPage, numberOfPages, previousPage, nextPage (firstPage, lastPage, search)
.RS
.RE
viewToolBar: scaleFactor, zoomIn, zoomOut (onePage, twoPages, oneColumn, twoColumns, fitToPage, fitToPageWidth, doNotScale, rotateLeft, rotateRight, fullscreen, presentation)
.RE
The order of the items in the list defines the order of the items in the toolbar. (See examples.)

Setting the keys "thumbnailWidth" and "thumbnailHeight" in the section "documentView" specifies the size of the thumbnails.

.SH EXAMPLES
.RS
The command
.RE
.B qpdfview foo.pdf#3#0.5 bar.pdf
.RS
opens foo.pdf in the first tab with the middle of page 3 aligned to the top of the tab and bar.pdf in the second tab at the beginning of the document.

Subsequent execution of the following commands
.RE
.B qpdfview --unique foo.pdf bar.pdf
.RS
.RE
.B qpdfview --unique foo.pdf#5
.RS
opens foo.pdf and bar.pdf, then reloads foo.pdf and displays its page 5.

Subsequent execution of the following commands
.RE
.B qpdfview --unique foo.pdf
.RS
.RE
.B qpdfview bar.pdf
.RS
.RE
.B qpdfview --unique foo1.pdf bar1.pdf
.RS
opens foo.pdf in the first window, bar.pdf in a second window and then foo1.pdf and bar1.pdf in additional tabs in the first window.

Adding the lines
.RE
.B fileToolBar=openInNewTab, refresh, saveCopy, print
.RS
.RE
.B editToolBar=firstPage, previousPage, currentPage, numberOfPages, nextPage, lastPage, search
.RS
.RE
.B viewToolBar=zoomOut, scaleFactor, zoomIn, oneColumn, twoColumns, rotateLeft, rotateRight
.RS
in section "mainWindow" of the configuration file leads to the corresponding items being displayed in the given order in the toolbars.

.SH BUGS
If you find a bug, please report it at
https://launchpad.net/qpdfview.
.SH AUTHOR
Benjamin Eltzner <b.eltzner@gmx.de>
